### ISSUE TITLE
Undocumented option -x or --exclude

### ISSUE THREAD

**Issue by abusque** [lttng/lttng-docs#10]
The -x or --exclude lttng command line flag is not present in the doc, but it is found in the manpage:

    -x, --exclude LIST

    Add exclusions to UST tracepoints: Events that match any of the
    items in the comma separated LIST are not enabled, even if they
    match a wildcard definition of the event.

    This option is also applicable with the -a, --all option, in which
    case all UST tracepoints are enabled except the ones whose names
    match any of the items in LIST.

**Comment by eepp** [comment]
This is documented as of f0287ae19ba24983cb17b0614879195ffd051e77.
