### ISSUE TITLE
Missing information for agent

### ISSUE THREAD

**Issue by PSRCode** [lttng/lttng-docs#14]
Installation instructions from ppa/source for python and java agent are not included and confuse users.

**Comment by eepp** [comment]
Please tell me which packages include the Java and Python agents, for all distributions. If a distribution does not provide a package including the Java and Python agents, I'll add a warning box indicating so, and that packages should be installed from source to enable those features.

**Comment by PSRCode** [comment]
Debian and Ubuntu provide:

liblttng-ust-python-agent0 (provide the .so required for the python agent)
python3-lttngust (provide the actual agent)
No package is provided for python2 for as of today..

*For now the python3 agent is not packaged correctly for Ubuntu and install the agent under site-package instead of dist-package which prevent python from importing it directly*

liblttnb-ust-java (provide the lib for java agent)
liblttng-ust-java-jni (provide the lib for java-jni agent)
liblttng-ust-agent-java (provide the java agent)
liblttng-ust-agent-java-jni (provide the java-jni agent)

As for the other distro you might want to check with @mjeanson.

Thanks

**Comment by eepp** [comment]
This was fixed a long time ago.
