### ISSUE TITLE
an error happened when I try the example in doc.

### ISSUE THREAD

**Issue by WandyLau** [lttng/lttng-docs#23]
hello-tp.o:(__tracepoints+0x18): undefined reference to `__tracepoint_provider_hello_world'
collect2: error: ld returned 1 exit status

I just follow the doc to produce a userspace program, hello.c. But this error arise when I try to build it.
Is there any wrong with the example?

**Comment by eepp** [comment]
Hello @WandyLau! You closed this issue without adding a comment: do you still consider this an issue, or did you find the issue was on your side?

**Comment by WandyLau** [comment]
Sorry, there is a typo in my program. This is not a issue. I have made it.
