### ISSUE TITLE
Kernel tracer not available

### ISSUE THREAD

**Issue by dmadboy** [lttng/lttng-docs#33]
I ran into this problem when I tried the tutorial.
the comment is :
`lttng list --kernel`
then wil get :
`Error: Unable to list kernel events: Kernel tracer not available`
My linux kernel is :
Ubuntu 18.04 Bionic Beaver
What' wrong with that? Can you help me? Thank you very much!

**Comment by liuhycn** [comment]
The same problem

**Comment by eepp** [comment]
This issue is not directly related to the LTTng Documentation.

Please use our [mailing list](https://lists.lttng.org/cgi-bin/mailman/listinfo/lttng-dev) or our `#lttng` IRC channel on [OFTC](https://www.oftc.net/) to get help with LTTng.
