### ISSUE TITLE
Images not loading when accessing docs via https://lttng.org/docs/

### ISSUE THREAD

**Issue by abusque** [lttng/lttng-docs#35]
Greetings,

I was accessing https://lttng.org/docs/, which appears to be an alias for the current latest version of the docs (currently https://lttng.org/docs/v2.12/), but I realized that the images won't load when accessing the docs from that URL, while they work just fine in the fully expanded URL. It looks like it's trying to resolve images under `/docs/images/`, when in fact they're only found under `/docs/v2.12/images/`.

It might be worth noting that https://docs.lttng.org/ redirects to https://lttng.org/docs/ as well. I had the first URL in my bookmarks, which redirected to the second, neither of which seem to appear on the site itself (the navbar links to the URL with the version in it, for instance).

**Comment by rwk-unil** [comment]
Hello.
I am experiencing the same behaviour, the images do not load.
The issue is well described above. 

`
https://lttng.org/docs/images/rotation.png => referenced in text, not found
https://lttng.org/docs/v2.12/images/rotation.png => displays
`

Cheers

**Comment by eepp** [comment]
This bug is not related to this project, which is only the contents of the LTTng Documentation.

Anyway, I fixed the website. Thank you for reporting and sorry for the wait.
