### ISSUE TITLE
Mention USDT probe support limitations 

### ISSUE THREAD

**Issue by christophebedard** [lttng/lttng-docs#38]
LTTng supports userspace SDT probes, but:

* only SDT probes that are not guarded by semaphores (although one can work around this/disable the semaphores)
* does not support probe parameters

While these limitations are mentioned [in this blog post](https://lttng.org/blog/2019/10/15/new-dynamic-user-space-tracing-in-lttng/), they are not mentioned in the docs and could cause some suprises.

I think it would be good to mention these limitations. If you agree, where in the docs would be the best place for it? Maybe under ["Create and enable an event rule"](https://lttng.org/docs/#doc-enabling-disabling-events)?

**Comment by eepp** [comment]
Those limitations are usually found in the manual pages, which are the official references for each `lttng` command, and, eventually, in the documentation of the liblttng-ctl C API.

See <https://lttng.org/man/1/lttng-enable-event/v2.12/#doc-userspace-probe> for example.

**Comment by christophebedard** [comment]
That still seems a bit hidden to me, but I see. Thanks for the feedback.
