### ISSUE TITLE
Can I disable local-file-writing in lttng-relayd to avoid the disk space overhead, only using it as a live viewer?

### ISSUE THREAD

**Issue by elftech** [lttng/lttng-docs#43]

**Comment by eepp** [comment]
Hello!

This is the wrong place to ask such a question: this is the LTTng Documentation repository, not a help forum.

Please see our [Community page](https://lttng.org/community/) to learn how to get help with LTTng.

The [mailing list](http://lists.lttng.org/cgi-bin/mailman/listinfo/lttng-dev) and the IRC channel (`#lttng` on OFTC) are the best ways to do so.
